name: Build with PyBind

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: textbook/git-checkout-submodule-action@2.0.0
      - uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.6

      - name: make
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_Python_PyBind=ON
          make

      - name: Install python module
        run: |
          pip install pytest, numpy
          python setup.py install

      - name: Test python module
        run: python -m pytest -vv -s Testing/test.py
