name: Windows Deploy

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          python-ver: 3.6
          COMPILER: Visual Studio 14 2015
        include:
          python-ver: 3.6
          COMPILER: Visual Studio 14 2015 Win64
          python-ver: 3.7
          COMPILER: Visual Studio 15 2017
        include:
          python-ver: 3.7
          COMPILER: Visual Studio 16 2017 Win64
    
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python-ver }}4
      - name: Build
        run: |
        mkdir build
        cd build
        cmake -G "{{ matrix.compiler }}" -DBUILD_Pytohn_PyBind:BOOL:ON -DCMAKE_BUILD_TYPE:String=Release --config Release ..
        cmake --build . --config Release
