
on: push

env:
  DO_PYTHON_BUILD: true
  PS4: '+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
  REPO_DIR: .
  BUILD_COMMIT: HEAD
  BUILD_DEPENDS: numpy wheel six
  TEST_DEPENDS: numpy pytest
  BDIST_PARAMS: ""
  UNICODE_WIDTH: 32

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-ver: [3.6, 3.7, 3.8]
        platform: [x86_64, i686]

    runs-on: ubuntu-latest
      
    env:
      PLAT: ${{ matrix.platform }}
      MB_PYTHON_VERSION: ${{ matrix.python-ver }}
      
    steps:
      - uses: actions/checkout@v2
      - uses: textbook/git-checkout-submodule-action@2.0.0
      - uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python-ver }}
      - name: Setup/run multibuild
        run: |
          source multibuild/common_utils.sh
          source multibuild/travis_linux_steps.sh
          source config.sh
          before_install

          DOCKER_IMAGE=quay.io/skvark/manylinux1_$PLAT
          build_multilinux $PLAT "build_wheel $REPO_DIR"

      # - name: Set up Python
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: python-ver

